{
 "title": "Instances At-a-Glance",
 "tags": [ "performance" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES ON telegraf FROM \"sqlserver_server_properties\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Host" },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_cpu",
     "metrics": [
      {
       "field": "TotalCPU",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "\"$Environment\"",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SQL Version",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"sql_version\" WHERE \"host\" =~ /^$Host$/ ",
     "select": [
      [
       { "params": [ "/^$Host$/" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]] Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"Avg._Disk_sec/Read\", $__interval) FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_instance]] Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"Avg._Disk_sec/Write\", $__interval) FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "bucketAggs": [
      {
       "fake": true,
       "field": "Name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_disk",
     "metrics": [
      {
       "field": "FreePCT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SELECT last(\"Percent_Free_Space\") FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'E:\\\\SQLTemp1' AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      {
       "field": "KillConnectionErrorsPerSec",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "UserErrorsPerSec",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "DeadlocksPerSec",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE ((\"counter\" = 'Transactions/sec' AND \"instance\" =~ /^Total/ ) OR \"counter\" = 'SQL Re-Compilations/sec' OR \"counter\" = 'SQL Compilations/sec' OR \"counter\" = 'Batch Requests/sec' OR \"counter\" = 'Number of Deadlocks/sec' ) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Number of Deadlocks/sec" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Processes blocked" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    }
   ]
  },
  {
   "title": "Wait Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_wait_category]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(max(\"wait_time_ms\"), $__interval) FROM \"sqlserver_waitstats\" WHERE \"host\" =~ /(?i)^$Host$/ AND \"wait_type\" != 'VDI_CLIENT_OTHER' AND $timeFilter GROUP BY time($__interval), \"wait_category\", \"server\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}