{
 "title": "Instance Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES ON telegraf FROM \"sqlserver_server_properties\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Server Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Offline",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovering",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_recovering" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_recoveryPending" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Restoring",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_restoring" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Suspect",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_suspect" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "kbytes",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"sql_version\" WHERE \"host\" =~ /^$Host$/ ",
     "select": [
      [
       { "params": [ "/^$Host$/" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "sql_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") AS \"Avg. Total %\", mean(\"Percent_User_Time\") AS \"Avg. User %\",mean(\"Percent_Privileged_Time\") AS \"Avg. Priv. %\" FROM \"sql_cpu\" WHERE \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"Avg. % User\", mean(\"usage_system\") AS \"Avg. % System\", mean(\"usage_iowait\") AS \"Avg. % IO Wait\", mean(\"usage_steal\") AS \"Avg. % Steal\"  FROM \"cpu\" WHERE \"host\" =~ /^(?i)$Host.*$/AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Query Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Query Store CPU ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_qs",
     "query": "SELECT mean(\"Query_Store_CPU_Usage\") AS \"cpu %\" FROM \"sql_qs\" WHERE \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"instance\"",
     "select": [
      [
       { "params": [ "/^$Host$/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Logical Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_qs",
     "query": "SELECT mean(\"Query_Store_logical_reads\") AS \"log. reads\" FROM \"sql_qs\" WHERE \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"instance\"",
     "select": [
      [
       { "params": [ "Query_Store_logical_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logical Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_qs",
     "query": "SELECT mean(\"Query_Store_logical_writes\") FROM \"sql_qs\" WHERE \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"instance\"",
     "select": [
      [
       { "params": [ "Query_Store_logical_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Physical Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sql_qs",
     "query": "SELECT mean(\"Query_Store_physical_reads\") FROM \"sql_qs\" WHERE \"host\" =~ /^(?i)$Host$/ AND $timeFilter GROUP BY time($interval), \"instance\"",
     "select": [
      [
       { "params": [ "Query_Store_physical_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE ((\"counter\" = 'Transactions/sec' AND \"instance\" =~ /^Total/ ) OR (\"counter\" = 'Write Transactions/sec' AND \"instance\" =~ /^Total/ ) OR (\"counter\" = 'XTP Memory Used (KB)' AND \"instance\" =~ /^Total/ )OR \"counter\" = 'SQL Re-Compilations/sec' OR \"counter\" = 'SQL Compilations/sec' OR \"counter\" = 'Batch Requests/sec' ) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "Batch Requests/sec" }
     ]
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT max(\"value\") FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Processes blocked' OR \"counter\" = 'User Connections')  AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($interval), \"counter\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Processes blocked" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "OR", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    },
    {
     "alias": "[[tag_counter]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(last(\"value\")) FROM \"sqlserver_performance\" WHERE \"counter\" = 'Number of Deadlocks/sec'  AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lock Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Lock Timeouts/sec",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"host\" =~ /^$Host$/ AND \"counter\" = 'Lock Timeouts/sec') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Timeouts/sec" }
     ],
     "timeField": "timestamp"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "lo" }
     ]
    }
   ]
  },
  {
   "title": "Waits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_wait_category]]",
       "groupBy": [
        { "params": [ "wait_category" ], "type": "tag" },
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "sqlserver_waitstats",
       "query": "SELECT non_negative_derivative(max(\"wait_time_ms\"), $__interval) FROM \"sqlserver_waitstats\" WHERE \"host\" =~ /^$Host$/ AND \"wait_type\" != 'VDI_CLIENT_OTHER' AND $timeFilter GROUP BY time($__interval), \"wait_category\", \"server\"",
       "select": [
        [
         { "params": [ "wait_time_ms" ], "type": "field" },
         { "params": [ "$interval" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Detail",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_clerk_type]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "clerk_type" ], "type": "tag" }
       ],
       "measurement": "sqlserver_memory_clerks",
       "select": [
        [
         { "params": [ "size_kb" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Page life expectancy",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE \"sql_instance\" =~ /^$Instance$/ AND ( \"counter\" = 'Page life expectancy' OR \"counter\" = 'Page reads/sec' OR \"counter\" = 'Page writes/sec' ) AND $timeFilter GROUP BY \"server\", \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Page life expectancy" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "counter" ], "type": "tag" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE \"host\" =~ /^$Host$/ AND ( \"counter\" = 'Page writes/sec' OR \"counter\" = 'Page reads/sec' OR \"counter\" = 'Lazy writes/sec' or \"counter\" = 'Buffer cache hit ratio' OR \"counter\" = 'Checkpoint pages/sec' OR \"counter\" = 'Page lookups/sec' OR \"counter\" = 'Readahead pages/sec') AND $timeFilter GROUP BY \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
        { "condition": "AND", "key": "counter", "operator": "=", "value": "Page writes/sec" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TempDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "TempDB Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE \"host\" =~ /^$Host$/ AND ( \"counter\" = 'Free Space in tempdb (KB)' OR \"counter\" = 'Version Store Size (KB)' ) AND $timeFilter GROUP BY \"server\", \"counter\", time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=~", "value": "/^$Instance$/" },
        { "condition": "AND", "key": "counter", "operator": "=", "value": "Free Space in tempdb (KB)" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Version Store Size (KB)" }
       ]
      }
     ]
    },
    {
     "title": "Temp Tables",
     "type": "graph",
     "description": "Temp table and table variable statistics.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "counter" ], "type": "tag" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Active Temp Tables' OR \"counter\" = 'Temp Tables For Destruction') AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY \"server\", \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Active Temp Tables" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Temp Tables Creation Rate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Temp Tables Creation Rate') AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Temp Tables Creation Rate" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(\"Avg._Disk_sec/Read\", $__interval) FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2'  GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"read_time\") / last(\"reads\")) AS \"Read\" FROM \"diskio\" WHERE (\"host\" =~ /^(?i)$Host.*$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2'  GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sql_disk",
     "query": "SELECT non_negative_derivative(\"Avg._Disk_sec/Write\", $__interval) FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2'  GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
     ]
    },
    {
     "alias": "[[tag_instanace]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"write_time\") / last(\"writes\")) AS \"Writes\" FROM \"diskio\" WHERE (\"host\" =~ /^(?i)$Host.*$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2'  GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Space",
     "type": "graph",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_instance]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "sql_disk",
       "query": "SELECT mean(\"Free_Megabytes\") FROM \"sql_disk\" WHERE (\"host\" =~ /(?i)^$Host$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2' AND \"instance\" != 'HarddiskVolume12'  GROUP BY time($interval), \"instance\"",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/(?i)^$Host$/" }
       ]
      },
      {
       "alias": "[[tag_instance]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "disk",
       "query": "SELECT mean(\"free\") FROM \"disk\" WHERE (\"host\" =~ /^$Host.*$/) AND $timeFilter  AND \"instance\" != 'HarddiskVolume1' AND \"instance\" != 'HarddiskVolume2' AND \"instance\" != 'HarddiskVolume12'  GROUP BY time($interval), \"host\"",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "alias": "[[tag_instance]]",
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "SELECT last(\"value\") AS \"Data Size\" FROM \"sqlserver_performance\" WHERE \"counter\" = 'Data File(s) Size (KB)' AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"instance\" fill(null) ORDER BY time DESC LIMIT 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Data Size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "AG Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) AS \"Log Send Queue\" FROM \"sqlserver_performance\" WHERE \"host\" =~ /^$Host$/ AND ( \"counter\" = 'Log Send Queue' OR \"counter\" = 'Log Apply Pending Queue' OR \"counter\" = 'Log Apply Ready Queue') AND $timeFilter GROUP BY time($__interval), \"counter\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
        { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Send Queue" }
       ],
       "timeField": "timestamp"
      },
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Transaction Delay' AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"counter\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Transaction Delay" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Replica Send/Receive",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "counter" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT non_negative_derivative(last(\"value\"),1s) FROM \"sqlserver_performance\" WHERE \"host\" =~ /^$Host$/ AND ( \"counter\" = 'Bytes Sent to Replica/sec' OR \"counter\" = 'Bytes Sent to Transport/sec' OR \"counter\" = 'Bytes Received from Replica/sec' OR \"counter\" = 'Log Bytes Received/sec') AND $timeFilter GROUP BY time($__interval), \"counter\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
        { "condition": "AND", "key": "counter", "operator": "=", "value": "Bytes Sent to Replica/sec" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Bytes Sent to Transport/sec" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Flush Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Log Flush Wait Time",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"host\" =~ /^$Host$/ AND \"counter\" = 'Log Flush Wait Time') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
        { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flush Wait Time" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Log Flushes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "counter" ], "type": "tag" }
       ],
       "measurement": "sqlserver_performance",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Log Bytes Flushed/sec' OR \"counter\" = 'Log Flushes/sec' ) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Log Bytes Flushed/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Log Bytes Flushed/sec" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Access Methods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE ((\"counter\" = 'Full Scans/sec' OR \"counter\" = 'Index Searches/sec' OR \"counter\" = 'Page Splits/sec' or \"counter\" = 'Forwarded Records/sec')) AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Full Scans/sec" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Index Searches/sec" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Page Splits/sec" }
       ]
      }
     ]
    },
    {
     "title": "Latch Waits/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Latch Waits/sec') AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Latch Waits/sec" }
       ]
      }
     ]
    },
    {
     "title": "Memory Manager",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_counter]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sqlserver_performance",
       "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"counter\" = 'Memory Grants Pending' OR \"counter\" = 'Target Server Memory (KB)' OR \"counter\" = 'Total Server Memory (KB)') AND \"host\" =~ /^$Host$/ AND $timeFilter GROUP BY time($__interval), \"counter\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "counter", "operator": "=", "value": "Memory Grants Pending" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Target Server Memory (KB)" },
        { "condition": "OR", "key": "counter", "operator": "=", "value": "Total Server Memory (KB)" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Workload Group Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU % By Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "CPU usage %" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Workload Group Stats" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Requests/Sec By Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "SQLServer:Workload Group Stats" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Requests completed/sec" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Blocked Tasks By Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_instance]]",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Workload Group Stats" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Blocked tasks" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}